"""empty message

Revision ID: 20c8de328537
Revises: eb637f3cd00e
Create Date: 2018-09-10 16:24:25.002138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c8de328537'
down_revision = 'eb637f3cd00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('descr', sa.String(length=255), nullable=False),
    sa.Column('cover', sa.String(length=512), nullable=False),
    sa.Column('createdate', sa.Date(), nullable=False),
    sa.Column('updatedate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('albumid', sa.Integer(), nullable=True),
    sa.Column('createdate', sa.Date(), nullable=False),
    sa.Column('updatedate', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['albumid'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    op.drop_table('album')
    # ### end Alembic commands ###
