"""empty message

Revision ID: 30456ac8668d
Revises: ef5231078cf3
Create Date: 2018-09-12 11:36:16.205874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30456ac8668d'
down_revision = 'ef5231078cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=False),
    sa.Column('updatedate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('article', 'updatedate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('tag', 'updatedate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('user', 'updatedate',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updatedate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('tag', 'updatedate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('article', 'updatedate',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_table('emotion')
    # ### end Alembic commands ###
