"""empty message

Revision ID: 917e1355a1a9
Revises: cc9b9fe86223
Create Date: 2018-09-21 17:55:48.696165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917e1355a1a9'
down_revision = 'cc9b9fe86223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('roletype', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'roletype')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
