"""empty message

Revision ID: b043ef722d4d
Revises: 30456ac8668d
Create Date: 2018-09-20 11:46:58.834636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b043ef722d4d'
down_revision = '30456ac8668d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catogory', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catogory', 'order')
    # ### end Alembic commands ###
