"""empty message

Revision ID: cc9b9fe86223
Revises: cdea1d498992
Create Date: 2018-09-21 17:24:26.069549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc9b9fe86223'
down_revision = 'cdea1d498992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('commenttype', sa.String(length=1), nullable=False),
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=False),
    sa.Column('updatedate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['articleid'], ['article.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('commentid', sa.Integer(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=False),
    sa.Column('updatedate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commentid'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('comment')
    # ### end Alembic commands ###
