"""empty message

Revision ID: eb637f3cd00e
Revises: c5f03a693799
Create Date: 2018-09-07 15:06:56.108443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb637f3cd00e'
down_revision = 'c5f03a693799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'article', 'catogory', ['catogoryid'], ['id'])
    op.create_foreign_key(None, 'article', 'user', ['authorid'], ['id'])
    op.add_column('user', sa.Column('descr', sa.Text(), nullable=False))
    op.add_column('user', sa.Column('interests', sa.String(length=127), nullable=False))
    op.add_column('user', sa.Column('job', sa.String(length=32), nullable=False))
    op.add_column('user', sa.Column('portrait', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('sex', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sex')
    op.drop_column('user', 'portrait')
    op.drop_column('user', 'job')
    op.drop_column('user', 'interests')
    op.drop_column('user', 'descr')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_constraint(None, 'article', type_='foreignkey')
    # ### end Alembic commands ###
