"""empty message

Revision ID: ef5231078cf3
Revises: 20c8de328537
Create Date: 2018-09-11 10:12:14.808512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5231078cf3'
down_revision = '20c8de328537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'album', 'user', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'album', type_='foreignkey')
    op.drop_column('album', 'userid')
    # ### end Alembic commands ###
